- .github/workflows/report.yaml
Add workflow using https://github.com/marketplace/actions/run-golangci-lint to provide multilinting.
Runs with `only-new-issues` to not annotate old code on PR (newish feature that may not behave correctly).
> Add meta linter golangci-lint

- cmd/ingest/ingest.go
- cmd/verify/verify.go
- internal/storage/storage.go
For the S3 uploader to work we need to wrap it in a go routine and we must explicitly close the writer one we are done.
> Fix S3 upload function

- .github/workflows/report.yaml
Seems all issues have been fixed and we can enable these all the time.
Fixes #21.
> Enable linters on every push

- cmd/ingest/ingest.go
- internal/storage/storage.go
This speeds up reading data from S3 as we don't have to read the entire file at once
> Use getObject instead of Downloader

- cmd/ingest/ingest.go
- cmd/verify/verify.go
- internal/config/config.go
- internal/storage/storage.go
Reworks the storage config and initiation so we don't have to use any if/else statements on the main code.
The new init format is simply : 
```go 
archive := storage.NewBackend(conf.Archive)
```
Where `Archive` is the storage config struct
```go
type Conf struct {
Type  string
S3    S3Conf
Posix posixConf
}
```
Fixes: #23
> Storage cleanup

- cmd/verify/verify.go
- go.mod
Avoid reading data into memory to fead into Crypt4GHReader, use a special reader to
return a supplied header first and then return data read from a "proper" reader.
> Reduce memory consumption for verify

- cmd/ingest/ingest.go
- cmd/ingest/ingest_test.go
- cmd/verify/verify.go
- internal/config/config.go
- internal/config/config_test.go
- internal/storage/storage.go
- internal/storage/storage_test.go
Moved some things that can be reused so they are initialized before the main loop. Also, verify storage backends upon creation.
Fixes #110, #111 and #112.
This currently uses ListObjectsV2 from s3 and requires that not to fail. That adds a requirement for s3 backends to have read permissions to the bucket. I believe that is acceptable (but worth mentioning especially).
> Bail out earlier on problems

- internal/config/config.go
- internal/config/config_test.go
we re-slice the requiredConfVars just for mapper removing the broker.routingkey
As pointed at: https://github.com/neicnordic/sda-helm/pull/47
> mapper does not require broker.routingkey

- cmd/finalize/finalize.go
- cmd/ingest/ingest.go
- cmd/intercept/intercept.go
- cmd/mapper/mapper.go
- cmd/verify/verify.go
- dev_utils/compose-sda.yml
- internal/broker/broker.go
Simplest solution to the problem of MQ re-connectivity
* Detect if the MQ connection closes and exit the main process.
* Rely on the deployment system to restart a stopped application.
fixes #152 
If we want to keep the main  process running a major rewrite is required.
> Mq detect connection failure

- .github/integration/setup/common/10_services.sh
- .github/integration/tests/common/30_ingest_test.sh
- cmd/ingest/ingest.go
- cmd/verify/verify.go
- dev_utils/compose-backend.yml
- dev_utils/compose-sda.yml
- dev_utils/config.yaml
- internal/database/db.go
- internal/database/db_test.go
Fixes #142.
Try to clean up some confusing naming issues as well - the database field `archive_file_checksum` now stores the checksum of what is actually stored in the archive rather than the decrypted checksum.
Decrypted checksum is stored in `decrypted_file_checksum`.
Sizes of archived and decrypted files are also kept (`archive_file_size` and `decrypted_file_size`).
> Store decrypted file size (and other attributes).

- internal/database/db.go
- internal/database/db_test.go
Retry database operation a configurable number of times.
Make operations idempotent (or close enough), specifically
MapFilesToDataset.
Also only transition files with status COMPLETED in MarkReady.
> Add db-retry mechanism

- .github/workflows/codeql-analysis.yml
- .github/workflows/create_docs.yaml
- .github/workflows/integration.yml
- .github/workflows/test.yml
use go 1.14 and 1.15 to test
bump actions version for python and go
cleanup comments
> update actions go version

- cmd/finalize/finalize.go
- cmd/finalize/finalize_test.go
- cmd/ingest/ingest.go
- cmd/ingest/ingest_test.go
- cmd/intercept/intercept.go
- cmd/intercept/intercept_test.go
- cmd/mapper/mapper.go
- cmd/mapper/mapper_test.go
- cmd/verify/verify.go
- cmd/verify/verify_test.go
- internal/broker/broker.go
- internal/broker/broker_test.go
- internal/config/config.go
Validation/JSON handling moved to broker package.
The unmarshalling test is stricter now and will complain if fields
from the JSON is missing in the destination struct.
(I'm ambivalent as to whatever having JSON handling in broker or a new package, so feel free to say if you think it's better in a new package.)
> Move to a unified ValidateJSON and fall-out from there

- .github/dependabot.yml
The AWS package are more or less being updated daily so to prevent spamming of PRs that just update one dependency we do a weekly set up dependency updates.
> Change dependabot to run weekly

- cmd/sync/sync.go
This allows sync to be triggered by either `accessionIDs` or `completed` message
> [sync] make JSON schema configurable

- .github/workflows/report.yaml
> update golang lint

- dev_utils/compose-backend.yml
- dev_utils/run_integration_test.sh
A few changes needed to make run_integration_test.sh work with the sda-pipeline when built using compose-backend.yml and compose-sda.yml
> Changes to dev_utils

- internal/broker/broker.go
- internal/broker/broker_test.go
- internal/broker/service_mock_test.go
By moving the creation of the NotifyPublish channel to the main MQ channel creation, instead of message publishing a deadlock is prevented. For some reason the channel was not cleared by listening on the response.
> [HotFix] for stalled ingestions

- .github/dependabot.yml
- .github/integration/setup/common/10_services.sh
- .github/integration/tests/common/10_trigger_failures.sh
- .github/workflows/integration.yml
- .github/workflows/shellcheck.yml
- dev_utils/make_certs.sh
- dev_utils/run_tests.sh
Closes #322 
changes:
- adjust shell scripts with a uniform syntax
- add shellcheck github action that runs only on all branches except master
- don't require python 3.6 as default version in integration tests
- tag whole team for checking dependency updates
> Feature/add shellcheck action #none

- go.mod
- go.sum
- internal/broker/broker.go
- internal/broker/broker_test.go
- internal/broker/service_mock_test.go
This is more of a proposal to move to a library that has support as the old one has not been updated in 2 years
> switch to rabbitmq managed library

- Dockerfile
related to https://github.com/golang/go/issues/51748
> add buildvcs flag to go build with false

- .github/integration/setup/common/20_tools.sh
- .github/integration/tests/common/10_trigger_failures.sh
- .github/integration/tests/common/8_bad_messages.sh
- .github/workflows/integration.yml
- cmd/ingest/ingest.go
- internal/broker/broker.go
- internal/broker/broker_test.go
This PR replaces all structs that were used to send messages to the error queue with one standard structure that is suitable for appending different kinds of info. In addition,
- sets output of json related errors to human readable
- fixes integration tests related to broken json errors (deactivated for now)
The logic behind using an empty interface as a holder for appended messages is to:
- allow for dynamic json so that when the file moves through the pipeline and relevant info accumulates, the exact message that triggered the error can be sent to the error queue
- handle different types, e.g. for broken or non json related errors where unmarshalling is not possible
- preserve the json format of the original message so that messages in the error queue are easy to parse, if needed
Closes …
> Refactor error queue messages

- cmd/finalize/finalize.go
This PR checks the nacking mechanisms in place for finalize. Messages that were previously requeued in case of a db related error could cause log flooding and occupy resources. These messages are now being moved to the error queue instead. 
Closes #345
> Check finalize service nacks for incorrect requeue

- .github/workflows/create_docs.yaml
github-pages update fails if there are no updates to the documentation, this aims to fix that.
> fix godocs github actions when no changes detected #none

- .github/integration/tests/posix/50_check_files.sh
- .github/integration/tests/posixheader/50_check_files.sh
- .github/integration/tests/s3/50_check_files.sh
- .github/integration/tests/s3header/50_check_files.sh
This PR is a fix for the integration tests and specifically the `50_check_files.sh` file, and specifically when comparing checksums for the different types of backends. It includes:
- Add path to the certificates for all tls enabled backends
- Fail in case no accession ids are found in the integration test
- Change the db query for s3 backend
Closes: #411
> Fix integration test folder

- cmd/backup/backup.go
- cmd/ingest/ingest.go
- cmd/verify/verify.go
- go.mod
- go.sum
- internal/config/config.go
moved from elixir-oslo/crypt4gh to neicnordic/crypt4gh - available with version 1.5.2 (https://pkg.go.dev/github.com/neicnordic/crypt4gh)
> move crypt4gh to neicnordic management

- .github/workflows/dependency-review.yml
the question is if we refine to fail only on `critical` and `moderate` or we fail on all of them ?
see https://github.com/actions/dependency-review-action#configuration
> Enforce dependency review not to update blindly

- cmd/backup/backup.go
- if `copyheader` is disabled, the backup service still requires keys, and it fails to start if they don't exist
> missing c4gh keys causes failed start in backup service

- .github/integration/tests/posixheader/50_check_files.sh
- .github/integration/tests/s3header/50_check_files.sh
- cmd/backup/backup.go
- cmd/backup/backup.md
The backup service is currently copying the file as in the same location as the archive (using the archive path). For the syncing between countries in BigPicture we need to copy the file in the original location (using the inbox path). 
This PR uses the original location in case the `copyHeader` parameter is set to true.
Co-Authored-By: kostas-kou <kkoumpouras@gmail.com>
> Add case for backup in original location

- cmd/mapper/mapper.go
- cmd/mapper/mapper.md
- cmd/verify/verify.go
- internal/database/db.go
The PR fixes the bug with the mapper, which was acknowledging the message even in case of failure. The fix is focused on the sync functionality for the BigPicture, where the messages are all arriving in the same time to the destination, therefore the mapper might receive the message before the file has been ingested. Therefore, in case of failure, the mapper sleeps for up to 5 minutes, to give time to the database to recover or for the file to get ingested.
(Also, includes a couple of spelling mistakes in verify and db)
> Add nack when mapping fails

- cmd/finalize/finalize.go
- cmd/finalize/finalize.md
- internal/database/db.go
- internal/database/db_test.go
This PR is similar to #487 and it fixes the same issue for finalize.
The fix is focused on the sync functionality for the BigPicture, where the messages are all arriving in the same time to the destination, therefore the finalize service might receive the message before the file has been ingested. Therefore, in case of failure, the finalize sleeps for up to 5 minutes, to give time to the database to recover or for the file to get ingested.
> Add nack when finalize fails

- cmd/verify/verify.go
If verify can't decrypt the entire file we need to send an error message.
> hotfix: [verify] send error message on decryption issues

- dev_utils/compose-no-tls.yml
- dev_utils/compose-sda.yml
The minio versions on the docker compose files are very (around 2 years) old and it don't run locally (at least for me). The PR updates the versions of the minio instance and uses the new way of passing credentials.
The version used here has been tested in sda-dashboard
> Update minio version in docker compose files

- cmd/ingest/ingest.md
- internal/database/db.go
The pull request is fixing an issue created by changes in the S3 Proxy. Specifically, the S3Proxy is now creating a row for each file that has been uploaded. That leads to ingest failing to insert the file, due to the unique constrains.
The PR checks the error when trying to insert the file and if it is related to the uniqueness constraint, it updates the file status instead.
> Update file if exists in ingest

- cmd/backup/backup.go
- cmd/finalize/finalize.go
- cmd/ingest/ingest.go
- cmd/intercept/intercept.go
- cmd/mapper/mapper.go
- cmd/notify/notify.go
- cmd/verify/verify.go
- dev_utils/compose-no-tls.yml
- dev_utils/compose-sda.yml
- internal/broker/broker.go
- internal/broker/broker_test.go
These seems to be the smallest changed needed in order to be able to handle a closed channel.
Using the library version of the Channel definition `*amqp.Channel` will require a much larger rewrite, specially of our tests.
Testing this is not straight forward as a channel can only be closed form the client side with the exemption of a channel time out event that happens after 30 min of inactivity.
To force a channel closure these actions needs to be taken:
* start MQ, DB and finalize
* pause the DB
* send a correct message to finalize
* wait for 30 min
closes #412
> Handle channel closures

- cmd/backup/backup.md
- cmd/finalize/finalize.md
- cmd/ingest/ingest.md
- cmd/mapper/mapper.md
- cmd/verify/verify.md
- internal/broker/broker.go
- internal/broker/broker_test.go
- internal/config/config.go
This fixes an issue when the queue contains to many messages and the time for processing each message takes so long that acking a message not being worked on times out after 30min.
- default number of messages to retrieve from the server is set to 2
- setting the prefetch number to 1 will allow for a true round-robin situation with multiple workers
Fixes #575
> Allow for setting message prefetch number

- .github/integration/tests/common/30_ingest_test.sh
- .github/integration/tests/posix/50_check_files.sh
- .github/integration/tests/posixheader/50_check_files.sh
- .github/integration/tests/s3/50_check_files.sh
- .github/integration/tests/s3header/50_check_files.sh
- .github/integration/tests/s3notls/40_ingest_test_notls.sh
- .github/integration/tests/s3notlsheader/40_ingest_test_notls.sh
- .github/integration/tests/sftp/50_check_files.sh
- .github/integration/tests/sftpheader/50_check_files.sh
- cmd/backup/backup.md
- cmd/finalize/finalize.go
- cmd/finalize/finalize.md
- cmd/ingest/ingest.md
- cmd/intercept/intercept.go
- cmd/mapper/mapper.go
- cmd/mapper/mapper.md
- cmd/orchestrate/orchestrate.go
- cmd/verify/verify.md
- dev_utils/compose-no-tls.yml
- dev_utils/compose-sda-standalone.yml
- dev_utils/compose-sda.yml
- dev_utils/run_integration_test.sh
- dev_utils/run_integration_test_no_tls.sh
- internal/config/config.go
- internal/database/db.go
- internal/database/db_test.go
- schemas/federated/dataset-deprecate.json
- schemas/federated/dataset-release.json
This will tag a new #minor version
This requires: https://github.com/neicnordic/sda-db/pull/91 and new `sda` schema, so **it breaks backwards compatibility with old db versions**
Introduces:
- `finalize` only adds the accessionId to the file, it does not mark it as `ready` anymore 
- `mapper` 
- `mapping` message assigns files to dataset
- `release` message marks `files` as `ready` in the db
- `deprecate` message marks the files as `disabled` in the db, added integration test for disabled
- `orchestrate` send also the release message (right now it waits for 1 minute)
- other changes will come to `sda-orchestrator` (python version) and `sda-download` in different PRs
- ~last commit should be removed once db PR it is approved~
> Feature/new dataset messages #minor
