neicnordic/sda-pipeline

go.mod
internal/broker/broker.go

The function takes the following input;
MQ connection struct, exchage, routingkey as strings and the message body as byte array
Fixes: #4

Add function to publish message to MQ

---

dev_utils/config.yaml
dev_utils/docker-compose.yml

Secret key needs to be minimum 8 characters.

S3 secret key default

---

cmd/finalize/config.go
cmd/finalize/finalize.go
internal/postgres/postgres.go

This update finalize to be on par with verify in terms of sctructuring.
* Code cleanup
* Use MarkReady function

Fixup finalize

---

cmd/finalize/finalize.go
cmd/verify/verify.go
internal/postgres/postgres.go

Added struct to wrap db instances and provide interfaces for the new struct.
This PR fixes #5

DB encapsulation and interface

---

cmd/verify/config.go
cmd/verify/verify.go
go.mod
internal/storage/storage.go

This PR aims at building a modularised storage backend interface, focusing on the addition of S3 file reading and uploading support.
Fixes #3

Shared storage components

---

internal/storage/storage.go

The defined method has been implemented in the Backend ifce and remains to do for Posix.

Add method for fetching size of files

---

dev_utils/config.yaml
dev_utils/docker-compose.yml

Fix default conf

---

dev_utils/docker-compose.yml

This tag should work with the docker-compose setup.

Use pipeline tag in sda-db

---

cmd/ingest/ingest.go
dev_utils/s3cmd.conf
internal/config/config.go
internal/storage/storage.go

* fixes s3 client config
* adds a `Downloader` to the S3 struct
* updates the config template so we only need to specify s3 or posix for the storage parts
* adds a s3cmd conf file for testing S3 against the minio instance in the docker-compose file.
* minor cleanup to make stuff work

Fix s3 download

---

internal/config/config.go

Minor refactoring of storage configuration to reduce code duplication.

Refactored storage configuration

---

cmd/mapper/mapper.go
internal/config/config.go
internal/postgres/postgres.go

* Import mapper from sda-mapper
* implement our config schema
* uses new message format
Fixes: #30

Import mapper

---

Dockerfile
hooks/build

Build containers for Golang based sda-pipeline. 
This should help to be able to run our integration tests for the sda-pipeline as well (but will require minor modifications there).

Support for building Docker containers

---

internal/config/config.go
internal/postgres/postgres.go

Allow all sslMode and enable passing key/cert in more cases 

---

cmd/verify/verify.go

Provide md5 checksum as well as sha256

---

schemas/inbox-upload.json
schemas/ingestion-accession-request.json
schemas/ingestion-accession.json
schemas/ingestion-completion.json
schemas/ingestion-trigger.json
schemas/ingestion-user-error.json

White space and formatting cleanup.

White space cleanup of json files

---

go.mod
go.sum
internal/postgres/postgres.go
internal/postgres/postgres_test.go

Adds test coverage for `internal/postgres`.

Unittests for postgres

---

internal/storage/storage.go
internal/storage/storage_test.go

Provide unittests for most of storage.

Unittests for storage

---

cmd/intercept/intercept.go
cmd/intercept/intercept_test.go
internal/config/config.go
internal/config/config_test.go

Simple service that parses messages coming from CRG based on the "type" field and passes them on to the correct internal routingkey.

Intercept skeleton

---

internal/config/config.go
internal/config/config_test.go

Do not require database configuration or routing key for intercept.

Lessen configuration requirements for intercept 

---

.dockerignore
.github/integration/setup/common/10_services.sh
.github/integration/setup/common/20_tools.sh
.github/integration/setup/common/22_create_and_encrypt_large_file.sh
.github/integration/setup/posix/1_posix_env_setup.sh
.github/integration/setup/posix/30_posix_permissions.sh
.github/integration/setup/s3/100_s3_storage_setup.sh
.github/integration/tests/common/10_trigger_failures.sh
.github/integration/tests/common/30_ingest_test.sh
.github/integration/tests/common/8_bad_messages.sh
.github/workflows/integration.yml
dev_utils/run_tests.sh

Some new scenarios for testing added, along with a simple micro framework for handling tests.
This is functional as regards to tests, but does not look as good as intended (I intend to add handling so it annotates with "Error" at the right line number and so on), but in standup just now, we said best to PR this for now.

Include some more tests in integration tests.

---

.github/integration/tests/common/30_ingest_test.sh

Show logs from earlier services if a service fail.

Better logs from tests

---

cmd/finalize/finalize.go
cmd/finalize/finalize_test.go
cmd/ingest/ingest.go
cmd/ingest/ingest_test.go
cmd/intercept/intercept.go
cmd/intercept/intercept_test.go
cmd/mapper/mapper.go
cmd/mapper/mapper_test.go
cmd/verify/verify.go
cmd/verify/verify_test.go
internal/broker/broker.go
internal/broker/broker_test.go

* Moves JSON validation to a separate function
* Added test for the above function
* Send messges on JSON error
* Send messages on file related errors for ingest and verify
fixes #130

Mq messages on error

---

.github/workflows/report.yaml

update golang-linter version

---

.github/dependabot.yml

Removing myself from the list :)

Adjust Dependabot reviewers

---

README.md

add sync service to main readme

---

.github/workflows/publish.yml

This will bump the patch number on each PR merge unless the commit message contains **&#35;none**. 
In order to bump the major or minor version add **&#35;major** or **&#35;minor** to the PR message.
**&#35;major** -> v1.2.3 > 2.0.0
**&#35;minor** -> v1.2.3 > 1.3.0
If a new tag is created the second part of the action will build an docker image and publish it to the GithHub Container Registry.
The new image can the be pulled by calling `docker pull ghcr.io/neicnordic/sda-pipeline:latest`
1. Action to automatically bump the tag on push to master or PR merge.
2. Builds new Docker image and published to GHCR when tag changes.
3. pushes to docker hub as well
#none Do not bump the version for this PR
@jbygdell who did the original code for this

publish docker hub and github registry #none

---

.github/integration/setup/common/10_services.sh
.github/integration/tests/common/10_trigger_failures.sh
.github/integration/tests/common/30_ingest_test.sh
.github/integration/tests/common/8_bad_messages.sh
.github/integration/tests/posix/50_check_files.sh
.github/integration/tests/s3/50_check_files.sh
dev_utils/README.md
dev_utils/compose-backend.yml

* Added a `certfixer` container to chown and chmod the certificates in the compose file
* Switched to https for MQ API calls
* Fix certificates for psql client connections
* White space cleanup
* bugfix in one script

Update integration tests with new DB and MQ images #none

---

.github/workflows/publish.yml

Reduce fetch depth to 1 in order to prevent issues with new tags

Reduce fetch depth #none

---

dev_utils/config-notls.yaml
dev_utils/config.yaml
internal/config/config.go

Change the logs format to json for the services in order to be easier to parse with grafana
Closes #361, Closes #360, Closes #362, Closes #363

Services logs in JSON format

---

dev_utils/run_integration_test.sh

Add missing certificates to make the requests to MQ and DB work, so that `run_integration_test.sh` can run locally. Also `client-cert.pem` permission needs to be 600 so the db connection can use it.

fix running integration tests locally #none

---

internal/config/config.go
internal/config/config_test.go

The exchange configuration of the broker was not set, leading to publishing to default. This PR fixes this issue

Bug fix/exchange config

---

cmd/backup/backup.md
cmd/finalize/finalize.md
cmd/ingest/ingest.md
cmd/intercept/intercept.md
cmd/mapper/mapper.md
cmd/verify/verify.md

Adds service configuration information to the pipeline services.

Adds config and communication to service docs

---

.github/workflows/test.yml

Start running tests against GO v1.20

Test GO code against v1.20

---

.github/integration/setup/common/22_create_and_encrypt_large_file.sh
.github/integration/setup/posix/31_posix_storage_setup.sh
.github/integration/setup/posixheader/31_posix_storage_setup.sh
.github/integration/setup/s3/100_s3_storage_setup.sh
.github/integration/setup/s3header/100_s3_storage_setup.sh
.github/integration/setup/s3notls/99_s3_storage_setup.sh
.github/integration/setup/s3notlsheader/99_s3_storage_setup.sh
.github/integration/setup/sftp/100_s3_storage_setup.sh
.github/integration/setup/sftpheader/100_s3_storage_setup.sh
.github/integration/tests/common/10_trigger_failures.sh
cmd/finalize/finalize.go
dev_utils/compose-no-tls.yml
dev_utils/compose-sda-standalone.yml
dev_utils/compose-sda.yml
internal/database/db.go

this is to prevent message requeuing so that the finalize gets blocked
- we check the id exists before we try to do anything with it and try to mark it as ready.
- add file for integration test (we skip for sftp header)
- update sda-db to v2.1.9

error if file with same id exists
